FROM nodered/node-red:latest

ENV TZ=America/Sao_Paulo

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Exports
EXPOSE 1880
#CMD [ "npm", "run", "debug" ]